name: Send JSON via HTTP Request Test

on:
  push:
    branches:
      - main

jobs:
  send_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read JSON file
        id: read_json
        uses: juliangruber/read-file-action@v1
        with:
          path: ${GITHUB_EVENT_PATH}
        
      - name: Send HTTP Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          method: POST
          url: http://35.167.90.132:8000/linter/lint-flow-json
          customHeaders: '{"Content-Type": "application/json"}'
          data: "{\"flowJSON\": ${{ steps.read_json.outputs.content }} }"

      - name: Show Response
        run: |
          echo $GITHUB_WORKSPACE/$GITHUB_EVENT_PATH
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
