name: Send JSON via HTTP Request

on:
  push:
    branches:
      - main

jobs:
  send_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON file
        id: read_json
        uses: actions/read-file@v1
        with:
          path: flows/starter.json
      
      - name: Send HTTP Request
        uses: peter-evans/http-request-action@v2
        with:
          method: POST
          url: https://httpbin.org/anything
          body: ${{ steps.read_json.outputs.content }}
