on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout test-flow-linter
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
          
    - id: files
      uses: jitterbit/get-changed-files@v1
  
    - name: Read JSON file
      id: read_json
      run: |
        for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo ${changed_file}
          echo "::set-output name=file_contents::$(cat ${changed_file})"
        done

    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://35.167.90.132:8000/linter/lint-flow-json'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{ "flowJSON": ${{ steps.read_json.outputs.file_contents }} }'
    
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
