name: Send JSON via HTTP Request Test

on:
  push:
    branches:
      - main

jobs:
  send_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read JSON file
        id: read_json
        uses: juliangruber/read-file-action@v1
        with:
          path: ./flows/starter.json
      
      - name: Echo package.json
        run: echo "${{ steps.read_json.outputs.content }}"
        
      - name: Send HTTP Request
        uses: fjogeleit/http-request-action@v1
        with:
          method: POST
          url: https://httpbin.org/anything
          customHeaders: '{"Content-Type": "application/json"}'
          data: ${{ steps.read_json.outputs.content }}
