on: [push]

jobs:
  flow-linter-job:
    runs-on: ubuntu-latest
    name: Lint Flows
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: files
        uses: jitterbit/get-changed-files@v1
          
      - name: Env
        run: |
          env
          git status
          
      - name: Lint Flows step
        id: lint-flow
        uses: pingone-davinci/flow-linter@d1.3
        with:
          ignore-warnings: 'false'
          flows: "/home/runner/work/test-flow-linter/test-flow-linter/${{ steps.files.outputs.added_modified }}"
  
      - name: Get lint flows results
        run: |
          echo "pass = ${{ steps.lint-flow.outputs.pass }}"
          echo "raw-results = ${{ steps.lint-flow.outputs.raw-results }}"
