on: [push]

jobs:
  flow-linter-job:
    runs-on: ubuntu-latest
    name: Lint Flows
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
          
      - name: Lint Flows step
        id: lint-flow
        uses: pingone-davinci/flow-linter@d1.4
        with:
          ignore-warnings: 'false'
          flows: ${{ steps.files.outputs.added_modified }}
  
      - name: Get lint flows results
        run: |
          echo "pass = ${{ steps.lint-flow.outputs.pass }}"
          echo "raw-results = ${{ steps.lint-flow.outputs.raw-results }}"
