on: [push]

jobs:
  flow-linter-job:
    runs-on: ubuntu-latest
    name: Lint Flows
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed-files
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before,
              head: context.payload.after
            });

            const changedFiles = response.data.files.map(file => file.filename);
            console.log("Changed Files:");
            console.log(changedFiles);
            core.setOutput('changed_files', changedFiles.join('\n'));

          
      - name: Lint Flows step
        id: lint-flow
        uses: pingone-davinci/flow-linter@d1.4
        with:
          ignore-warnings: 'false'
          flows: ${{ steps.changed-files.ouptuts.changed_files }}
  
      - name: Get lint flows results
        run: |
          echo "pass = ${{ steps.lint-flow.outputs.pass }}"
          echo "raw-results = ${{ steps.lint-flow.outputs.raw-results }}"
