on: [push]

jobs:
  flow-linter-job:
    runs-on: ubuntu-latest
    name: Lint Flows
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }}
          changed_files=$(git diff --name-only main...${{ github.sha }})
          echo "Changed files = $changed_files"
          
      - name: Lint Flows step
        id: lint-flow
        uses: pingone-davinci/flow-linter@d1.4
        with:
          ignore-warnings: 'false'
          flows: "${{ steps.changed-files.ouptuts.changed_files }}"
      # Use the output from the `hello` step
      - name: Get lint flows results
        run: |
          echo "pass = ${{ steps.lint-flow.outputs.pass }}"
          echo "raw-results = ${{ steps.lint-flow.outputs.raw-results }}"
